### ISSUE TITLE
Build error with Linux 6.9

### ISSUE THREAD

**Issue by ilgrosso** [intel/ivsc-driver#48]
```
Building module:
Cleaning build area...
make -j21 KERNELRELEASE=6.9.3-060903-generic KERNELRELEASE=6.9.3-060903-generic KERNEL_SRC=/lib/modules/6.9.3-060903-generic/build...(bad exit status: 2)
ERROR (dkms apport): binary package for ivsc-driver: 1.0.0 not found
Error! Bad return status for module build on kernel: 6.9.3-060903-generic (x86_64)
Consult /var/lib/dkms/ivsc-driver/1.0.0/build/make.log for more information.
```

**Comment by ilgrosso** [comment]
Here it follows the content from `/var/lib/dkms/ivsc-driver/1.0.0/build/make.log`:

```
  CC [M]  /var/lib/dkms/ivsc-driver/1.0.0/build/drivers/mfd/ljca.o
  CC [M]  /var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.o
  CC [M]  /var/lib/dkms/ivsc-driver/1.0.0/build/drivers/gpio/gpio-ljca.o
  CC [M]  /var/lib/dkms/ivsc-driver/1.0.0/build/drivers/i2c/busses/i2c-ljca.o
  CC [M]  /var/lib/dkms/ivsc-driver/1.0.0/build/drivers/misc/mei/spi-vsc.o
  CC [M]  /var/lib/dkms/ivsc-driver/1.0.0/build/drivers/misc/mei/hw-vsc.o
  CC [M]  /var/lib/dkms/ivsc-driver/1.0.0/build/drivers/misc/ivsc/intel_vsc.o
  CC [M]  /var/lib/dkms/ivsc-driver/1.0.0/build/drivers/misc/ivsc/mei_csi.o
  CC [M]  /var/lib/dkms/ivsc-driver/1.0.0/build/drivers/misc/ivsc/mei_ace.o
  CC [M]  /var/lib/dkms/ivsc-driver/1.0.0/build/drivers/misc/ivsc/mei_pse.o
  CC [M]  /var/lib/dkms/ivsc-driver/1.0.0/build/drivers/misc/ivsc/mei_ace_debug.o
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c: In function ‘ljca_spi_transfer_one’:
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:220:41: error: implicit declaration of function ‘spi_master_get_devdata’; did you mean ‘spi_controller_get_devdata’? [-Werror=implicit-function-declaration]
  220 |         struct ljca_spi_dev *ljca_spi = spi_master_get_devdata(master);
      |                                         ^~~~~~~~~~~~~~~~~~~~~~
      |                                         spi_controller_get_devdata
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:220:41: warning: initialization of ‘struct ljca_spi_dev *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
In file included from ./include/vdso/const.h:5,
                 from ./include/linux/const.h:4,
                 from ./include/linux/bits.h:5,
                 from ./include/linux/ioport.h:13,
                 from ./include/linux/acpi.h:12,
                 from /var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:8:
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:224:34: error: invalid use of undefined type ‘struct spi_master’
  224 |         div = DIV_ROUND_UP(master->max_speed_hz, xfer->speed_hz) / 2 - 1;
      |                                  ^~
./include/uapi/linux/const.h:34:40: note: in definition of macro ‘__KERNEL_DIV_ROUND_UP’
   34 | #define __KERNEL_DIV_ROUND_UP(n, d) (((n) + (d) - 1) / (d))
      |                                        ^
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:224:15: note: in expansion of macro ‘DIV_ROUND_UP’
  224 |         div = DIV_ROUND_UP(master->max_speed_hz, xfer->speed_hz) / 2 - 1;
      |               ^~~~~~~~~~~~
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c: In function ‘ljca_spi_probe’:
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:250:16: error: assignment to ‘struct spi_master *’ from incompatible pointer type ‘struct spi_controller *’ [-Werror=incompatible-pointer-types]
  250 |         master = spi_alloc_master(&pdev->dev, sizeof(*ljca_spi));
      |                ^
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:255:18: warning: assignment to ‘struct ljca_spi_dev *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  255 |         ljca_spi = spi_master_get_devdata(master);
      |                  ^
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:259:25: error: invalid use of undefined type ‘struct spi_master’
  259 |         ljca_spi->master->dev.of_node = pdev->dev.of_node;
      |                         ^~
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:262:45: error: invalid use of undefined type ‘struct spi_master’
  262 |         ACPI_COMPANION_SET(&ljca_spi->master->dev, ACPI_COMPANION(&pdev->dev));
      |                                             ^~
./include/linux/acpi.h:58:60: note: in definition of macro ‘ACPI_COMPANION_SET’
   58 | #define ACPI_COMPANION_SET(dev, adev)   set_primary_fwnode(dev, (adev) ? \
      |                                                            ^~~
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:264:15: error: invalid use of undefined type ‘struct spi_master’
  264 |         master->bus_num = -1;
      |               ^~
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:265:15: error: invalid use of undefined type ‘struct spi_master’
  265 |         master->mode_bits = SPI_CPHA | SPI_CPOL;
      |               ^~
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:266:15: error: invalid use of undefined type ‘struct spi_master’
  266 |         master->prepare_message = ljca_spi_prepare_message;
      |               ^~
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:267:15: error: invalid use of undefined type ‘struct spi_master’
  267 |         master->transfer_one = ljca_spi_transfer_one;
      |               ^~
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:268:15: error: invalid use of undefined type ‘struct spi_master’
  268 |         master->auto_runtime_pm = false;
      |               ^~
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:269:15: error: invalid use of undefined type ‘struct spi_master’
  269 |         master->max_speed_hz = LJCA_SPI_BUS_MAX_HZ;
      |               ^~
  LD [M]  /var/lib/dkms/ivsc-driver/1.0.0/build/mei_ace_debug.o
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:271:15: error: implicit declaration of function ‘devm_spi_register_master’; did you mean ‘devm_spi_register_controller’? [-Werror=implicit-function-declaration]
  271 |         ret = devm_spi_register_master(&pdev->dev, master);
      |               ^~~~~~~~~~~~~~~~~~~~~~~~
      |               devm_spi_register_controller
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:280:9: error: implicit declaration of function ‘spi_master_put’; did you mean ‘spi_dev_put’? [-Werror=implicit-function-declaration]
  280 |         spi_master_put(master);
      |         ^~~~~~~~~~~~~~
      |         spi_dev_put
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c: In function ‘ljca_spi_dev_remove’:
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:286:37: error: implicit declaration of function ‘spi_master_get’; did you mean ‘spi_dev_get’? [-Werror=implicit-function-declaration]
  286 |         struct spi_master *master = spi_master_get(platform_get_drvdata(pdev));
      |                                     ^~~~~~~~~~~~~~
      |                                     spi_dev_get
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:286:37: warning: initialization of ‘struct spi_master *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:287:41: warning: initialization of ‘struct ljca_spi_dev *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  287 |         struct ljca_spi_dev *ljca_spi = spi_master_get_devdata(master);
      |                                         ^~~~~~~~~~~~~~~~~~~~~~
  LD [M]  /var/lib/dkms/ivsc-driver/1.0.0/build/gpio-ljca.o
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c: In function ‘ljca_spi_dev_suspend’:
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:298:16: error: implicit declaration of function ‘spi_master_suspend’; did you mean ‘spi_controller_suspend’? [-Werror=implicit-function-declaration]
  298 |         return spi_master_suspend(master);
      |                ^~~~~~~~~~~~~~~~~~
      |                spi_controller_suspend
  LD [M]  /var/lib/dkms/ivsc-driver/1.0.0/build/mei_ace.o
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c: In function ‘ljca_spi_dev_resume’:
/var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.c:305:16: error: implicit declaration of function ‘spi_master_resume’; did you mean ‘spi_controller_resume’? [-Werror=implicit-function-declaration]
  305 |         return spi_master_resume(master);
      |                ^~~~~~~~~~~~~~~~~
      |                spi_controller_resume
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:244: /var/lib/dkms/ivsc-driver/1.0.0/build/drivers/spi/spi-ljca.o] Errore 1
make[3]: *** Attesa per i processi non terminati....
make[2]: *** [/usr/src/linux-headers-6.9.3-060903-generic/Makefile:1925: /var/lib/dkms/ivsc-driver/1.0.0/build] Errore 2
make[1]: *** [Makefile:240: __sub-make] Errore 2
make[1]: uscita dalla directory «/usr/src/linux-headers-6.9.3-060903-generic»
make: *** [Makefile:43: all] Errore 2
```

**Comment by wentongwu** [comment]
@ilgrosso could you please use the upstream driver? thanks
